services:
  frontend:
    container_name: frontend
    build:
      context: frontend
    tty: true
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true
    extra_hosts:
      - host.docker.internal:host-gateway

  backend:
    container_name: backend
    build:
      context: backend
    tty: true
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:8
    command: --collation-server=utf8mb4_0900_bin
      --transaction-isolation=READ-COMMITTED
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 53306:3306
